before_install:
- npm install -g grunt-cli
before_deploy:
- grunt before-deploy
after_deploy:
- grunt after-deploy
language: node_js
node_js:
- '0.10'
notifications:
  email: false
env:
  global:
  - secure: I0iRs4x9Rm6KHEp+S4VkKqOteEfeCJ9+L5dPoCK/mQ8kyQ5/PZE8sG86RKXDhFyPmOM0pOg9mYO+qi70KQVk+wexb0ZC63XanXF8nrRE0/mcf+751nxfGaVq9nSuGf83uNGWf5u7fE3TKzAcP5nb4fqQ8BYjXtHDBn6ls4L5rHg=
deploy:
  provider: npm
  email: stephan@thehoodiefirm.com
  on:
    all_branches: true
    tags: true
  api_key:
    secure: VI0sSbdC0kxrdU4a7wtUTzybLZBT7vVOTdhQTzzEWWJGEH36bFyej9eUuIhchrl4yLtgUtA2n7B5Sddwbio44QOqYPWv6h2MOv8hRid9pFS/NynZTbbq0cV1N9wUcfymidtimHyG0m4ujc+eUNEjIZXQum+PERlvfWd9PhxgVpg=
